name: Publish to GitHub Pages

on:
  push:
    branches: [ main ]

  workflow_dispatch:

concurrency:
  cancel-in-progress: false
  group: "pages"

jobs:
  build-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get

      - run: flutter build -v web --release

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'build/web/'

      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

permissions:
  contents: read
  id-token: write
  pages: write
